### PR TITLE
fix stdin.js

### PR DESCRIPTION
**Pull request by yukkurisinai**
get expectPipeIn by the right way

### CODE REVIEW

**Comment by wooorm** [comment]
Nice catch! Do you know the support of `Stat#isFIFO`? I couldn’t find it anywhere...

**Comment by anko** [comment]
Is this really correct?

Old method:

    $ node -e "console.log(\!process.stdin.isTTY)" <<< "hello"
    true
    $ node -e "console.log(\!process.stdin.isTTY)"            
    false

Proposed method:

    $ node -e "console.log(require('fs').fstatSync(0).isFIFO())" <<< "hello"
    false
    $ node -e "console.log(require('fs').fstatSync(0).isFIFO())"            
    false

I think our tests don't touch this, hence why Travis shows OK.

**Comment by wooorm** [comment]
@yukkurisinai @anko Interesing, they do seem to work for `echo "hello" | node ex.js`, where `ex.js` looks as follows:

```js
console.log(!process.stdin.isTTY);
console.log(require('fs').fstatSync(0).isFIFO())
```

Yields:

```
true
true
```

But for `node ex.js <<< "hello"`:

```
true
false
```

**Comment by wooorm** [comment]
@yukkurisinai What was the case where this failed?

**Comment by yukkurisinai** [comment]
when I use mdast in drone.io, `!process.stdin.isTTY` is always true :(
In addition to this, If I write gulpfile.js as below, it output `true`.

`​`​`​js
var shell = require("gulp-shell");
gulp.task("foobar", shell.task("node -e \"console.log(\!process.stdin.isTTY)\""));
`​`​`​

**Comment by yukkurisinai** [comment]
In the first place, mdast check `program.files.length` at line 37. why must mdast check `!process.stdin.isTTY` ?

**Comment by yukkurisinai** [comment]
sorry to my poor english :(

**Comment by wooorm** [comment]
@yukkurisinai because when not piping in, passing no files is an error. When piping in, passing files is an error!

**Comment by yukkurisinai** [comment]
ok, I understood... I thought that when passing files, mdast can ignore pipe.

**Comment by wooorm** [comment]
Okay, I tested a lot, it has to do with subprocesses. And I couldn’t find a method, either `!process.stdin.isTTY`, `require('fs').fstatSync(0).isFIFO()`, or `!require('tty').isatty(process.stdin)` which detects it everywhere...

**Comment by yukkurisinai** [comment]
umm... If you can ignore `<<<` , I think `require('fs').fstatSync(0).isFIFO()` is the best way.

**Comment by wooorm** [comment]
But I’d rather not ignore it though!

**Comment by yukkurisinai** [comment]
ok, I investigation about "<<<". please wait a moment to conclude plz...

**Comment by wooorm** [comment]
Yeah I’m testing it out too. Thanks for helping!

**Comment by yukkurisinai** [comment]
if user use "<<<", isFIFO can't catch pipe. so, I wrote a code.

```javascript
var expectPipeIn = !process.stdin.isTTY ? !process.stdin.isTTY : fs.fstatSync(0).isFIFO();
```

How is this?

**Comment by wooorm** [comment]
```
stdin: undefined false false  // `<<<` pipe in bash
stdin: undefined false false  // `<<<` pipe in gulp
stdin: undefined true false   // `|` pipe in bash
stdin: undefined true false   // `|` pipe in gulp
stdin: true      false true   // `files` in bash
stdin: undefined false false  // `files` in gulp
```

As you can see from line 6, it’s exactly the same as line 1 and 2 (meaning it
can’t be detected).

**Comment by wooorm** [comment]
@anko How standard is `<<<` it seems pretty hidden?

**Comment by wooorm** [comment]
I was able to get *almost* all cases to work:

```
mdast # throws
mdast readme.md
echo 'hello' | mdast
mdast <<< hello
```

...and in gulp (see below for example code):

```
mdast readme.md
echo 'hello' mdast
mdast <<< hello
```

By only throwing if there’s definitly a TTY.

However, this doesn’t work for the below case (which keeps hanging)

```js
var gulp = require('gulp');
var shell = require('gulp-shell');

var task = shell.task('mdast'); # this hangs.

gulp.task('default', task);
```

**Comment by wooorm** [comment]
Plus, the system outlined above: In bash and gulp: Throws on `echo 'hello' | mdast readme.md`, but chooses `readme.md` on `mdast readme.md <<< hello` (without error).

I’m not sure if “hanging” / waiting for stdin, in a child-process is such a problem when not given files is a big problem. I think I’ll just add it :)

**Comment by wooorm** [comment]
Thanks for your work and help. This ensures that at least no false errors are thrown. It will be released when GH-57 is merged.

**Comment by yukkurisinai** [comment]
thank you very much!

**Pull request closed without merging**
