### PR TITLE
Add mdast-deku to plugin list

### PR DESCRIPTION
**Pull request by ulrikaugustsson**

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks for the nice work. Could you however place it after `eush77/mdast-defsplit`, I try my best to keep the list alphabetical ;)

**Comment by ulrikaugustsson** [comment]
@wooorm sure, I'm on windows right now so can't fix this with 1 clean commit. Do you want me to close this PR and create a new one or should I wait until I get home to my linux machine?

**Comment by wooorm** [comment]
I’d like one commit if possible. If possible on one PR. Sorry for the nitpicking. :/

**Comment by ulrikaugustsson** [comment]
Okey, I'll fix the PR when I get home. :)

**Pull request closed without merging**
